// Generated by Bisonc++ V4.05.00 on Thu, 30 Apr 2015 04:26:50 +0900

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {287, 0}, // 1: Program ->  <empty>
     {287, 1}, // 2: Program ->  FuncList
     {287, 1}, // 3: Program ->  DeclList
     {287, 2}, // 4: Program ->  DeclList FuncList
     {289, 1}, // 5: DeclList ->  Declaration
     {289, 2}, // 6: DeclList ->  DeclList Declaration
     {288, 1}, // 7: FuncList ->  Function
     {288, 2}, // 8: FuncList ->  FuncList Function
     {290, 3}, // 9: Declaration (SEMICOLON) ->  Type IdentList SEMICOLON
     {293, 1}, // 10: IdentList ->  identifier
     {293, 3}, // 11: IdentList (COMA) ->  IdentList COMA identifier
     {294, 1}, // 12: identifier (ID) ->  ID
     {294, 4}, // 13: identifier (ID) ->  ID LBRACKET INTNUM RBRACKET
     {291, 5}, // 14: Function (ID) ->  Type ID LPAREN RPAREN CompoundStmt
     {291, 6}, // 15: Function (ID) ->  Type ID LPAREN ParamList RPAREN CompoundStmt
     {296, 2}, // 16: ParamList ->  Type identifier
     {296, 4}, // 17: ParamList (COMA) ->  ParamList COMA Type identifier
     {292, 1}, // 18: Type (INT) ->  INT
     {292, 1}, // 19: Type (FLOAT) ->  FLOAT
     {295, 3}, // 20: CompoundStmt (LBRACE) ->  LBRACE StmtList RBRACE
     {295, 4}, // 21: CompoundStmt (LBRACE) ->  LBRACE DeclList StmtList RBRACE
     {297, 0}, // 22: StmtList ->  <empty>
     {297, 2}, // 23: StmtList ->  StmtList Stmt
     {298, 1}, // 24: Stmt ->  AssignStmt
     {298, 1}, // 25: Stmt ->  CallStmt
     {298, 1}, // 26: Stmt ->  RetStmt
     {298, 1}, // 27: Stmt ->  WhileStmt
     {298, 1}, // 28: Stmt ->  ForStmt
     {298, 1}, // 29: Stmt ->  IfStmt
     {298, 1}, // 30: Stmt ->  SwitchStmt
     {298, 1}, // 31: Stmt ->  CompoundStmt
     {298, 1}, // 32: Stmt (SEMICOLON) ->  SEMICOLON
     {299, 2}, // 33: AssignStmt (SEMICOLON) ->  Assign SEMICOLON
     {306, 3}, // 34: Assign (ID) ->  ID EQUAL Expr
     {306, 6}, // 35: Assign (ID) ->  ID LBRACKET Expr RBRACKET EQUAL Expr
     {300, 2}, // 36: CallStmt (SEMICOLON) ->  Call SEMICOLON
     {308, 3}, // 37: Call (ID) ->  ID LPAREN RPAREN
     {308, 4}, // 38: Call (ID) ->  ID LPAREN ArgList RPAREN
     {301, 2}, // 39: RetStmt (RETURN) ->  RETURN SEMICOLON
     {301, 3}, // 40: RetStmt (RETURN) ->  RETURN Expr SEMICOLON
     {302, 5}, // 41: WhileStmt (WHILE) ->  WHILE LPAREN Expr RPAREN Stmt
     {302, 6}, // 42: WhileStmt (DO) ->  DO Stmt WHILE LPAREN Expr RPAREN
     {303, 9}, // 43: ForStmt (FOR) ->  FOR LPAREN Assign SEMICOLON Expr SEMICOLON Assign RPAREN Stmt
     {304, 5}, // 44: IfStmt (IF) ->  IF LPAREN Expr RPAREN Stmt
     {304, 7}, // 45: IfStmt (IF) ->  IF LPAREN Expr RPAREN Stmt ELSE Stmt
     {305, 7}, // 46: SwitchStmt (SWITCH) ->  SWITCH LPAREN identifier RPAREN LBRACE CaseList RBRACE
     {310, 1}, // 47: CaseList ->  CaseOnlyList
     {310, 4}, // 48: CaseList (DEFAULT) ->  CaseOnlyList DEFAULT COLON StmtList
     {310, 6}, // 49: CaseList (DEFAULT) ->  CaseOnlyList DEFAULT COLON StmtList BREAK SEMICOLON
     {311, 0}, // 50: CaseOnlyList ->  <empty>
     {311, 5}, // 51: CaseOnlyList (CASE) ->  CaseOnlyList CASE INTNUM COLON StmtList
     {311, 7}, // 52: CaseOnlyList (CASE) ->  CaseOnlyList CASE INTNUM COLON StmtList BREAK SEMICOLON
     {312, 1}, // 53: BinOp (MDOP) ->  MDOP
     {312, 1}, // 54: BinOp (ASOP) ->  ASOP
     {312, 1}, // 55: BinOp (UNOP) ->  UNOP
     {312, 1}, // 56: BinOp (RLOP) ->  RLOP
     {312, 1}, // 57: BinOp (EQOP) ->  EQOP
     {307, 2}, // 58: Expr (UNOP) ->  UNOP Expr
     {307, 3}, // 59: Expr ->  Expr BinOp Expr
     {307, 1}, // 60: Expr ->  Call
     {307, 1}, // 61: Expr (INTNUM) ->  INTNUM
     {307, 1}, // 62: Expr (FLOATNUM) ->  FLOATNUM
     {307, 1}, // 63: Expr (ID) ->  ID
     {307, 4}, // 64: Expr (ID) ->  ID LBRACKET Expr RBRACKET
     {307, 3}, // 65: Expr (LPAREN) ->  LPAREN Expr RPAREN
     {309, 1}, // 66: ArgList ->  Expr
     {309, 3}, // 67: ArgList (COMA) ->  ArgList COMA Expr
     {313, 1}, // 68: Program_$ ->  Program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_DEF}, {  9} },               
    { {     287}, {  1} }, // Program    
    { {     288}, {  2} }, // FuncList   
    { {     289}, {  3} }, // DeclList   
    { {     291}, {  4} }, // Function   
    { {     290}, {  5} }, // Declaration
    { {     292}, {  6} }, // Type       
    { {     268}, {  7} }, // INT        
    { {     269}, {  8} }, // FLOAT      
    { {       0}, { -1} },               
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  5} },            
    { {     291}, {  9} }, // Function
    { {     292}, { 10} }, // Type    
    { {     268}, {  7} }, // INT     
    { {     269}, {  8} }, // FLOAT   
    { {       0}, { -2} },            
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  7} },               
    { {     288}, { 11} }, // FuncList   
    { {     290}, { 12} }, // Declaration
    { {     291}, {  4} }, // Function   
    { {     292}, {  6} }, // Type       
    { {     268}, {  7} }, // INT        
    { {     269}, {  8} }, // FLOAT      
    { {       0}, { -3} },               
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       265}, { 13} }, // ID        
    { {       293}, { 14} }, // IdentList 
    { {       294}, { 15} }, // identifier
    { {         0}, {  0} },              
};

SR__ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       265}, { 16} }, // ID
    { {         0}, {  0} },      
};

SR__ s_11[] =
{
    { { REQ_DEF}, {  5} },            
    { {     291}, {  9} }, // Function
    { {     292}, { 10} }, // Type    
    { {     268}, {  7} }, // INT     
    { {     269}, {  8} }, // FLOAT   
    { {       0}, { -4} },            
};

SR__ s_12[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_13[] =
{
    { { REQ_DEF}, {   3} },            
    { {     263}, {  17} }, // LPAREN  
    { {     280}, {  18} }, // LBRACKET
    { {       0}, { -12} },            
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       285}, { 19} }, // SEMICOLON
    { {       286}, { 20} }, // COMA     
    { {         0}, {  0} },             
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 17} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  6} },             
    { {       264}, { 21} }, // RPAREN   
    { {       296}, { 22} }, // ParamList
    { {       292}, { 23} }, // Type     
    { {       268}, {  7} }, // INT      
    { {       269}, {  8} }, // FLOAT    
    { {         0}, {  0} },             
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       266}, { 24} }, // INTNUM
    { {         0}, {  0} },          
};

SR__ s_19[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       294}, { 25} }, // identifier
    { {       265}, { 26} }, // ID        
    { {         0}, {  0} },              
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  3} },                
    { {       295}, { 27} }, // CompoundStmt
    { {       282}, { 28} }, // LBRACE      
    { {         0}, {  0} },                
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       264}, { 29} }, // RPAREN
    { {       286}, { 30} }, // COMA  
    { {         0}, {  0} },          
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       294}, { 31} }, // identifier
    { {       265}, { 26} }, // ID        
    { {         0}, {  0} },              
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       281}, { 32} }, // RBRACKET
    { {         0}, {  0} },            
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_26[] =
{
    { { REQ_DEF}, {   2} },            
    { {     280}, {  18} }, // LBRACKET
    { {       0}, { -12} },            
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_28[] =
{
    { { REQ_DEF}, {   7} },               
    { {     297}, {  33} }, // StmtList   
    { {     289}, {  34} }, // DeclList   
    { {     290}, {   5} }, // Declaration
    { {     292}, {  35} }, // Type       
    { {     268}, {   7} }, // INT        
    { {     269}, {   8} }, // FLOAT      
    { {       0}, { -22} },               
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  3} },                
    { {       295}, { 36} }, // CompoundStmt
    { {       282}, { 28} }, // LBRACE      
    { {         0}, {  0} },                
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       292}, { 37} }, // Type 
    { {       268}, {  7} }, // INT  
    { {       269}, {  8} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, { 22} },                
    { {       283}, { 38} }, // RBRACE      
    { {       298}, { 39} }, // Stmt        
    { {       299}, { 40} }, // AssignStmt  
    { {       300}, { 41} }, // CallStmt    
    { {       301}, { 42} }, // RetStmt     
    { {       302}, { 43} }, // WhileStmt   
    { {       303}, { 44} }, // ForStmt     
    { {       304}, { 45} }, // IfStmt      
    { {       305}, { 46} }, // SwitchStmt  
    { {       295}, { 47} }, // CompoundStmt
    { {       285}, { 48} }, // SEMICOLON   
    { {       306}, { 49} }, // Assign      
    { {       308}, { 50} }, // Call        
    { {       270}, { 51} }, // RETURN      
    { {       271}, { 52} }, // WHILE       
    { {       272}, { 53} }, // DO          
    { {       273}, { 54} }, // FOR         
    { {       274}, { 55} }, // IF          
    { {       276}, { 56} }, // SWITCH      
    { {       282}, { 28} }, // LBRACE      
    { {       265}, { 57} }, // ID          
    { {         0}, {  0} },                
};

SR__ s_34[] =
{
    { { REQ_DEF}, {   6} },               
    { {     297}, {  58} }, // StmtList   
    { {     290}, {  12} }, // Declaration
    { {     292}, {  35} }, // Type       
    { {     268}, {   7} }, // INT        
    { {     269}, {   8} }, // FLOAT      
    { {       0}, { -22} },               
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       293}, { 14} }, // IdentList 
    { {       294}, { 15} }, // identifier
    { {       265}, { 26} }, // ID        
    { {         0}, {  0} },              
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       294}, { 59} }, // identifier
    { {       265}, { 26} }, // ID        
    { {         0}, {  0} },              
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       285}, { 60} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       285}, { 61} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  9} },             
    { {       285}, { 62} }, // SEMICOLON
    { {       307}, { 63} }, // Expr     
    { {       262}, { 64} }, // UNOP     
    { {       308}, { 65} }, // Call     
    { {       266}, { 66} }, // INTNUM   
    { {       267}, { 67} }, // FLOATNUM 
    { {       265}, { 68} }, // ID       
    { {       263}, { 69} }, // LPAREN   
    { {         0}, {  0} },             
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 70} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 21} },                
    { {       298}, { 71} }, // Stmt        
    { {       299}, { 40} }, // AssignStmt  
    { {       300}, { 41} }, // CallStmt    
    { {       301}, { 42} }, // RetStmt     
    { {       302}, { 43} }, // WhileStmt   
    { {       303}, { 44} }, // ForStmt     
    { {       304}, { 45} }, // IfStmt      
    { {       305}, { 46} }, // SwitchStmt  
    { {       295}, { 47} }, // CompoundStmt
    { {       285}, { 48} }, // SEMICOLON   
    { {       306}, { 49} }, // Assign      
    { {       308}, { 50} }, // Call        
    { {       270}, { 51} }, // RETURN      
    { {       271}, { 52} }, // WHILE       
    { {       272}, { 53} }, // DO          
    { {       273}, { 54} }, // FOR         
    { {       274}, { 55} }, // IF          
    { {       276}, { 56} }, // SWITCH      
    { {       282}, { 28} }, // LBRACE      
    { {       265}, { 57} }, // ID          
    { {         0}, {  0} },                
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 72} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 73} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 74} }, // LPAREN
    { {         0}, {  0} },          
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  4} },            
    { {       257}, { 75} }, // EQUAL   
    { {       280}, { 76} }, // LBRACKET
    { {       263}, { 77} }, // LPAREN  
    { {         0}, {  0} },            
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 22} },                
    { {       283}, { 78} }, // RBRACE      
    { {       298}, { 39} }, // Stmt        
    { {       299}, { 40} }, // AssignStmt  
    { {       300}, { 41} }, // CallStmt    
    { {       301}, { 42} }, // RetStmt     
    { {       302}, { 43} }, // WhileStmt   
    { {       303}, { 44} }, // ForStmt     
    { {       304}, { 45} }, // IfStmt      
    { {       305}, { 46} }, // SwitchStmt  
    { {       295}, { 47} }, // CompoundStmt
    { {       285}, { 48} }, // SEMICOLON   
    { {       306}, { 49} }, // Assign      
    { {       308}, { 50} }, // Call        
    { {       270}, { 51} }, // RETURN      
    { {       271}, { 52} }, // WHILE       
    { {       272}, { 53} }, // DO          
    { {       273}, { 54} }, // FOR         
    { {       274}, { 55} }, // IF          
    { {       276}, { 56} }, // SWITCH      
    { {       282}, { 28} }, // LBRACE      
    { {       265}, { 57} }, // ID          
    { {         0}, {  0} },                
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       285}, { 79} }, // SEMICOLON
    { {       312}, { 80} }, // BinOp    
    { {       261}, { 81} }, // MDOP     
    { {       260}, { 82} }, // ASOP     
    { {       262}, { 83} }, // UNOP     
    { {       259}, { 84} }, // RLOP     
    { {       258}, { 85} }, // EQOP     
    { {         0}, {  0} },             
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  8} },            
    { {       307}, { 86} }, // Expr    
    { {       262}, { 64} }, // UNOP    
    { {       308}, { 65} }, // Call    
    { {       266}, { 66} }, // INTNUM  
    { {       267}, { 67} }, // FLOATNUM
    { {       265}, { 68} }, // ID      
    { {       263}, { 69} }, // LPAREN  
    { {         0}, {  0} },            
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   3} },            
    { {     280}, {  87} }, // LBRACKET
    { {     263}, {  77} }, // LPAREN  
    { {       0}, { -63} },            
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  8} },            
    { {       307}, { 88} }, // Expr    
    { {       262}, { 64} }, // UNOP    
    { {       308}, { 65} }, // Call    
    { {       266}, { 66} }, // INTNUM  
    { {       267}, { 67} }, // FLOATNUM
    { {       265}, { 68} }, // ID      
    { {       263}, { 69} }, // LPAREN  
    { {         0}, {  0} },            
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  8} },            
    { {       307}, { 89} }, // Expr    
    { {       262}, { 64} }, // UNOP    
    { {       308}, { 65} }, // Call    
    { {       266}, { 66} }, // INTNUM  
    { {       267}, { 67} }, // FLOATNUM
    { {       265}, { 68} }, // ID      
    { {       263}, { 69} }, // LPAREN  
    { {         0}, {  0} },            
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       271}, { 90} }, // WHILE
    { {         0}, {  0} },         
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       306}, { 91} }, // Assign
    { {       265}, { 92} }, // ID    
    { {         0}, {  0} },          
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  8} },            
    { {       307}, { 93} }, // Expr    
    { {       262}, { 64} }, // UNOP    
    { {       308}, { 65} }, // Call    
    { {       266}, { 66} }, // INTNUM  
    { {       267}, { 67} }, // FLOATNUM
    { {       265}, { 68} }, // ID      
    { {       263}, { 69} }, // LPAREN  
    { {         0}, {  0} },            
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       294}, { 94} }, // identifier
    { {       265}, { 26} }, // ID        
    { {         0}, {  0} },              
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  8} },            
    { {       307}, { 95} }, // Expr    
    { {       262}, { 64} }, // UNOP    
    { {       308}, { 65} }, // Call    
    { {       266}, { 66} }, // INTNUM  
    { {       267}, { 67} }, // FLOATNUM
    { {       265}, { 68} }, // ID      
    { {       263}, { 69} }, // LPAREN  
    { {         0}, {  0} },            
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  8} },            
    { {       307}, { 96} }, // Expr    
    { {       262}, { 64} }, // UNOP    
    { {       308}, { 65} }, // Call    
    { {       266}, { 66} }, // INTNUM  
    { {       267}, { 67} }, // FLOATNUM
    { {       265}, { 68} }, // ID      
    { {       263}, { 69} }, // LPAREN  
    { {         0}, {  0} },            
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, { 10} },            
    { {       264}, { 97} }, // RPAREN  
    { {       309}, { 98} }, // ArgList 
    { {       307}, { 99} }, // Expr    
    { {       262}, { 64} }, // UNOP    
    { {       308}, { 65} }, // Call    
    { {       266}, { 66} }, // INTNUM  
    { {       267}, { 67} }, // FLOATNUM
    { {       265}, { 68} }, // ID      
    { {       263}, { 69} }, // LPAREN  
    { {         0}, {  0} },            
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {   8} },            
    { {       307}, { 100} }, // Expr    
    { {       262}, {  64} }, // UNOP    
    { {       308}, {  65} }, // Call    
    { {       266}, {  66} }, // INTNUM  
    { {       267}, {  67} }, // FLOATNUM
    { {       265}, {  68} }, // ID      
    { {       263}, {  69} }, // LPAREN  
    { {         0}, {   0} },            
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_86[] =
{
    { { REQ_DEF}, {   3} },         
    { {     312}, {  80} }, // BinOp
    { {     262}, {  83} }, // UNOP 
    { {       0}, { -58} },         
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {   8} },            
    { {       307}, { 101} }, // Expr    
    { {       262}, {  64} }, // UNOP    
    { {       308}, {  65} }, // Call    
    { {       266}, {  66} }, // INTNUM  
    { {       267}, {  67} }, // FLOATNUM
    { {       265}, {  68} }, // ID      
    { {       263}, {  69} }, // LPAREN  
    { {         0}, {   0} },            
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {   8} },          
    { {       264}, { 102} }, // RPAREN
    { {       312}, {  80} }, // BinOp 
    { {       261}, {  81} }, // MDOP  
    { {       260}, {  82} }, // ASOP  
    { {       262}, {  83} }, // UNOP  
    { {       259}, {  84} }, // RLOP  
    { {       258}, {  85} }, // EQOP  
    { {         0}, {   0} },          
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {   8} },          
    { {       264}, { 103} }, // RPAREN
    { {       312}, {  80} }, // BinOp 
    { {       261}, {  81} }, // MDOP  
    { {       260}, {  82} }, // ASOP  
    { {       262}, {  83} }, // UNOP  
    { {       259}, {  84} }, // RLOP  
    { {       258}, {  85} }, // EQOP  
    { {         0}, {   0} },          
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       263}, { 104} }, // LPAREN
    { {         0}, {   0} },          
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       285}, { 105} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       257}, { 75} }, // EQUAL   
    { {       280}, { 76} }, // LBRACKET
    { {         0}, {  0} },            
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   8} },          
    { {       264}, { 106} }, // RPAREN
    { {       312}, {  80} }, // BinOp 
    { {       261}, {  81} }, // MDOP  
    { {       260}, {  82} }, // ASOP  
    { {       262}, {  83} }, // UNOP  
    { {       259}, {  84} }, // RLOP  
    { {       258}, {  85} }, // EQOP  
    { {         0}, {   0} },          
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       264}, { 107} }, // RPAREN
    { {         0}, {   0} },          
};

SR__ s_95[] =
{
    { { REQ_DEF}, {   7} },         
    { {     312}, {  80} }, // BinOp
    { {     261}, {  81} }, // MDOP 
    { {     260}, {  82} }, // ASOP 
    { {     262}, {  83} }, // UNOP 
    { {     259}, {  84} }, // RLOP 
    { {     258}, {  85} }, // EQOP 
    { {       0}, { -34} },         
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   8} },            
    { {       281}, { 108} }, // RBRACKET
    { {       312}, {  80} }, // BinOp   
    { {       261}, {  81} }, // MDOP    
    { {       260}, {  82} }, // ASOP    
    { {       262}, {  83} }, // UNOP    
    { {       259}, {  84} }, // RLOP    
    { {       258}, {  85} }, // EQOP    
    { {         0}, {   0} },            
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {       264}, { 109} }, // RPAREN
    { {       286}, { 110} }, // COMA  
    { {         0}, {   0} },          
};

SR__ s_99[] =
{
    { { REQ_DEF}, {   7} },         
    { {     312}, {  80} }, // BinOp
    { {     261}, {  81} }, // MDOP 
    { {     260}, {  82} }, // ASOP 
    { {     262}, {  83} }, // UNOP 
    { {     259}, {  84} }, // RLOP 
    { {     258}, {  85} }, // EQOP 
    { {       0}, { -66} },         
};

SR__ s_100[] =
{
    { { REQ_DEF}, {   7} },         
    { {     312}, {  80} }, // BinOp
    { {     261}, {  81} }, // MDOP 
    { {     260}, {  82} }, // ASOP 
    { {     262}, {  83} }, // UNOP 
    { {     259}, {  84} }, // RLOP 
    { {     258}, {  85} }, // EQOP 
    { {       0}, { -59} },         
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   8} },            
    { {       281}, { 111} }, // RBRACKET
    { {       312}, {  80} }, // BinOp   
    { {       261}, {  81} }, // MDOP    
    { {       260}, {  82} }, // ASOP    
    { {       262}, {  83} }, // UNOP    
    { {       259}, {  84} }, // RLOP    
    { {       258}, {  85} }, // EQOP    
    { {         0}, {   0} },            
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {  21} },                
    { {       298}, { 112} }, // Stmt        
    { {       299}, {  40} }, // AssignStmt  
    { {       300}, {  41} }, // CallStmt    
    { {       301}, {  42} }, // RetStmt     
    { {       302}, {  43} }, // WhileStmt   
    { {       303}, {  44} }, // ForStmt     
    { {       304}, {  45} }, // IfStmt      
    { {       305}, {  46} }, // SwitchStmt  
    { {       295}, {  47} }, // CompoundStmt
    { {       285}, {  48} }, // SEMICOLON   
    { {       306}, {  49} }, // Assign      
    { {       308}, {  50} }, // Call        
    { {       270}, {  51} }, // RETURN      
    { {       271}, {  52} }, // WHILE       
    { {       272}, {  53} }, // DO          
    { {       273}, {  54} }, // FOR         
    { {       274}, {  55} }, // IF          
    { {       276}, {  56} }, // SWITCH      
    { {       282}, {  28} }, // LBRACE      
    { {       265}, {  57} }, // ID          
    { {         0}, {   0} },                
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {   8} },            
    { {       307}, { 113} }, // Expr    
    { {       262}, {  64} }, // UNOP    
    { {       308}, {  65} }, // Call    
    { {       266}, {  66} }, // INTNUM  
    { {       267}, {  67} }, // FLOATNUM
    { {       265}, {  68} }, // ID      
    { {       263}, {  69} }, // LPAREN  
    { {         0}, {   0} },            
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {   8} },            
    { {       307}, { 114} }, // Expr    
    { {       262}, {  64} }, // UNOP    
    { {       308}, {  65} }, // Call    
    { {       266}, {  66} }, // INTNUM  
    { {       267}, {  67} }, // FLOATNUM
    { {       265}, {  68} }, // ID      
    { {       263}, {  69} }, // LPAREN  
    { {         0}, {   0} },            
};

SR__ s_106[] =
{
    { { REQ_TOKEN}, {  21} },                
    { {       298}, { 115} }, // Stmt        
    { {       299}, {  40} }, // AssignStmt  
    { {       300}, {  41} }, // CallStmt    
    { {       301}, {  42} }, // RetStmt     
    { {       302}, {  43} }, // WhileStmt   
    { {       303}, {  44} }, // ForStmt     
    { {       304}, {  45} }, // IfStmt      
    { {       305}, {  46} }, // SwitchStmt  
    { {       295}, {  47} }, // CompoundStmt
    { {       285}, {  48} }, // SEMICOLON   
    { {       306}, {  49} }, // Assign      
    { {       308}, {  50} }, // Call        
    { {       270}, {  51} }, // RETURN      
    { {       271}, {  52} }, // WHILE       
    { {       272}, {  53} }, // DO          
    { {       273}, {  54} }, // FOR         
    { {       274}, {  55} }, // IF          
    { {       276}, {  56} }, // SWITCH      
    { {       282}, {  28} }, // LBRACE      
    { {       265}, {  57} }, // ID          
    { {         0}, {   0} },                
};

SR__ s_107[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       282}, { 116} }, // LBRACE
    { {         0}, {   0} },          
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       257}, { 117} }, // EQUAL
    { {         0}, {   0} },         
};

SR__ s_109[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   8} },            
    { {       307}, { 118} }, // Expr    
    { {       262}, {  64} }, // UNOP    
    { {       308}, {  65} }, // Call    
    { {       266}, {  66} }, // INTNUM  
    { {       267}, {  67} }, // FLOATNUM
    { {       265}, {  68} }, // ID      
    { {       263}, {  69} }, // LPAREN  
    { {         0}, {   0} },            
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {   8} },          
    { {       264}, { 119} }, // RPAREN
    { {       312}, {  80} }, // BinOp 
    { {       261}, {  81} }, // MDOP  
    { {       260}, {  82} }, // ASOP  
    { {       262}, {  83} }, // UNOP  
    { {       259}, {  84} }, // RLOP  
    { {       258}, {  85} }, // EQOP  
    { {         0}, {   0} },          
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {   8} },             
    { {       285}, { 120} }, // SEMICOLON
    { {       312}, {  80} }, // BinOp    
    { {       261}, {  81} }, // MDOP     
    { {       260}, {  82} }, // ASOP     
    { {       262}, {  83} }, // UNOP     
    { {       259}, {  84} }, // RLOP     
    { {       258}, {  85} }, // EQOP     
    { {         0}, {   0} },             
};

SR__ s_115[] =
{
    { { REQ_DEF}, {   2} },        
    { {     275}, { 121} }, // ELSE
    { {       0}, { -44} },        
};

SR__ s_116[] =
{
    { { DEF_RED}, {   3} },                
    { {     310}, { 122} }, // CaseList    
    { {     311}, { 123} }, // CaseOnlyList
    { {       0}, { -50} },                
};

SR__ s_117[] =
{
    { { REQ_TOKEN}, {   8} },            
    { {       307}, { 124} }, // Expr    
    { {       262}, {  64} }, // UNOP    
    { {       308}, {  65} }, // Call    
    { {       266}, {  66} }, // INTNUM  
    { {       267}, {  67} }, // FLOATNUM
    { {       265}, {  68} }, // ID      
    { {       263}, {  69} }, // LPAREN  
    { {         0}, {   0} },            
};

SR__ s_118[] =
{
    { { REQ_DEF}, {   7} },         
    { {     312}, {  80} }, // BinOp
    { {     261}, {  81} }, // MDOP 
    { {     260}, {  82} }, // ASOP 
    { {     262}, {  83} }, // UNOP 
    { {     259}, {  84} }, // RLOP 
    { {     258}, {  85} }, // EQOP 
    { {       0}, { -67} },         
};

SR__ s_119[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {       306}, { 125} }, // Assign
    { {       265}, {  92} }, // ID    
    { {         0}, {   0} },          
};

SR__ s_121[] =
{
    { { REQ_TOKEN}, {  21} },                
    { {       298}, { 126} }, // Stmt        
    { {       299}, {  40} }, // AssignStmt  
    { {       300}, {  41} }, // CallStmt    
    { {       301}, {  42} }, // RetStmt     
    { {       302}, {  43} }, // WhileStmt   
    { {       303}, {  44} }, // ForStmt     
    { {       304}, {  45} }, // IfStmt      
    { {       305}, {  46} }, // SwitchStmt  
    { {       295}, {  47} }, // CompoundStmt
    { {       285}, {  48} }, // SEMICOLON   
    { {       306}, {  49} }, // Assign      
    { {       308}, {  50} }, // Call        
    { {       270}, {  51} }, // RETURN      
    { {       271}, {  52} }, // WHILE       
    { {       272}, {  53} }, // DO          
    { {       273}, {  54} }, // FOR         
    { {       274}, {  55} }, // IF          
    { {       276}, {  56} }, // SWITCH      
    { {       282}, {  28} }, // LBRACE      
    { {       265}, {  57} }, // ID          
    { {         0}, {   0} },                
};

SR__ s_122[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       283}, { 127} }, // RBRACE
    { {         0}, {   0} },          
};

SR__ s_123[] =
{
    { { REQ_DEF}, {   3} },           
    { {     278}, { 128} }, // DEFAULT
    { {     277}, { 129} }, // CASE   
    { {       0}, { -47} },           
};

SR__ s_124[] =
{
    { { REQ_DEF}, {   7} },         
    { {     312}, {  80} }, // BinOp
    { {     261}, {  81} }, // MDOP 
    { {     260}, {  82} }, // ASOP 
    { {     262}, {  83} }, // UNOP 
    { {     259}, {  84} }, // RLOP 
    { {     258}, {  85} }, // EQOP 
    { {       0}, { -35} },         
};

SR__ s_125[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       264}, { 130} }, // RPAREN
    { {         0}, {   0} },          
};

SR__ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_127[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_128[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       284}, { 131} }, // COLON
    { {         0}, {   0} },         
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       266}, { 132} }, // INTNUM
    { {         0}, {   0} },          
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {  21} },                
    { {       298}, { 133} }, // Stmt        
    { {       299}, {  40} }, // AssignStmt  
    { {       300}, {  41} }, // CallStmt    
    { {       301}, {  42} }, // RetStmt     
    { {       302}, {  43} }, // WhileStmt   
    { {       303}, {  44} }, // ForStmt     
    { {       304}, {  45} }, // IfStmt      
    { {       305}, {  46} }, // SwitchStmt  
    { {       295}, {  47} }, // CompoundStmt
    { {       285}, {  48} }, // SEMICOLON   
    { {       306}, {  49} }, // Assign      
    { {       308}, {  50} }, // Call        
    { {       270}, {  51} }, // RETURN      
    { {       271}, {  52} }, // WHILE       
    { {       272}, {  53} }, // DO          
    { {       273}, {  54} }, // FOR         
    { {       274}, {  55} }, // IF          
    { {       276}, {  56} }, // SWITCH      
    { {       282}, {  28} }, // LBRACE      
    { {       265}, {  57} }, // ID          
    { {         0}, {   0} },                
};

SR__ s_131[] =
{
    { { DEF_RED}, {   2} },            
    { {     297}, { 134} }, // StmtList
    { {       0}, { -22} },            
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       284}, { 135} }, // COLON
    { {         0}, {   0} },         
};

SR__ s_133[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_134[] =
{
    { { REQ_DEF}, {  22} },                
    { {     279}, { 136} }, // BREAK       
    { {     298}, {  39} }, // Stmt        
    { {     299}, {  40} }, // AssignStmt  
    { {     300}, {  41} }, // CallStmt    
    { {     301}, {  42} }, // RetStmt     
    { {     302}, {  43} }, // WhileStmt   
    { {     303}, {  44} }, // ForStmt     
    { {     304}, {  45} }, // IfStmt      
    { {     305}, {  46} }, // SwitchStmt  
    { {     295}, {  47} }, // CompoundStmt
    { {     285}, {  48} }, // SEMICOLON   
    { {     306}, {  49} }, // Assign      
    { {     308}, {  50} }, // Call        
    { {     270}, {  51} }, // RETURN      
    { {     271}, {  52} }, // WHILE       
    { {     272}, {  53} }, // DO          
    { {     273}, {  54} }, // FOR         
    { {     274}, {  55} }, // IF          
    { {     276}, {  56} }, // SWITCH      
    { {     282}, {  28} }, // LBRACE      
    { {     265}, {  57} }, // ID          
    { {       0}, { -48} },                
};

SR__ s_135[] =
{
    { { DEF_RED}, {   2} },            
    { {     297}, { 137} }, // StmtList
    { {       0}, { -22} },            
};

SR__ s_136[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       285}, { 138} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR__ s_137[] =
{
    { { REQ_DEF}, {  22} },                
    { {     279}, { 139} }, // BREAK       
    { {     298}, {  39} }, // Stmt        
    { {     299}, {  40} }, // AssignStmt  
    { {     300}, {  41} }, // CallStmt    
    { {     301}, {  42} }, // RetStmt     
    { {     302}, {  43} }, // WhileStmt   
    { {     303}, {  44} }, // ForStmt     
    { {     304}, {  45} }, // IfStmt      
    { {     305}, {  46} }, // SwitchStmt  
    { {     295}, {  47} }, // CompoundStmt
    { {     285}, {  48} }, // SEMICOLON   
    { {     306}, {  49} }, // Assign      
    { {     308}, {  50} }, // Call        
    { {     270}, {  51} }, // RETURN      
    { {     271}, {  52} }, // WHILE       
    { {     272}, {  53} }, // DO          
    { {     273}, {  54} }, // FOR         
    { {     274}, {  55} }, // IF          
    { {     276}, {  56} }, // SWITCH      
    { {     282}, {  28} }, // LBRACE      
    { {     265}, {  57} }, // ID          
    { {       0}, { -51} },                
};

SR__ s_138[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_139[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       285}, { 140} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR__ s_140[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}




