AREA SP
AREA FP
AREA VR
AREA MEM
LAB START
MOVE 0 FP
MOVE 0 SP
ADD SP@ 1 SP
MOVE END MEM(SP@)
JMP Fmain
LAB END
LAB Fback
ADD SP@ 1 SP
MOVE FP@ MEM(SP@)
MOVE SP@ FP
MOVE MEM(FP@(-2))@ VR(0)
MOVE 0 VR(1)
SUB VR(0)@ VR(1)@ VR(2)
JMPZ VR(2)@ L0
JMP L1
LAB L0
MOVE 1 VR(2)
JMP L2
LAB L1
MOVE 0 VR(2)
LAB L2
JMPZ VR(2)@ L4
MOVE 0 VR(0)
I2F VR(0)@ VR(0)
MOVE VR(0)@ VR
MOVE FP@ SP
MOVE MEM(SP@)@ FP
SUB SP@ 1 SP
JMP MEM(SP@)@
JMP L3
LAB L4
LAB L3
MOVE 4.000000 VR(0)
MOVE MEM(FP@(-3))@ VR(1)
I2F VR(1)@ VR(1)
FDIV VR(0)@ VR(1)@ VR(2)
MOVE VR(2)@ MEM(SP@)(1)
MOVE MEM(FP@(-3))@ VR(0)
MOVE 2 VR(1)
ADD VR(0)@ VR(1)@ VR(3)
MOVE VR(3)@ MEM(SP@)(2)
MOVE MEM(FP@(-2))@ VR(0)
MOVE 1 VR(1)
SUB VR(0)@ VR(1)@ VR(3)
MOVE VR(3)@ MEM(SP@)(3)
ADD SP@ 4 SP
MOVE L5 MEM(SP@)
JMP Fback
LAB L5
MOVE VR@ VR(0)
SUB SP@ 4 SP
MOVE MEM(SP@)(1)@ VR(2)
FSUB VR(2)@ VR(0)@ VR(1)
MOVE VR(1)@ VR
MOVE FP@ SP
MOVE MEM(SP@)@ FP
SUB SP@ 1 SP
JMP MEM(SP@)@
MOVE FP@ SP
MOVE MEM(SP@)@ FP
SUB SP@ 1 SP
JMP MEM(SP@)@
LAB Fmain
ADD SP@ 1 SP
MOVE FP@ MEM(SP@)
MOVE SP@ FP
ADD SP@ 1 SP
MOVE MEM(FP@(1)) MEM(SP@)(1)
ADD SP@ 2 SP
MOVE L6 MEM(SP@)
JMP Fscanfi
LAB L6
SUB SP@ 2 SP
MOVE 1 VR(0)
MOVE VR(0)@ MEM(SP@)(1)
MOVE MEM(FP@(1))@ VR(0)
MOVE VR(0)@ MEM(SP@)(2)
ADD SP@ 3 SP
MOVE L7 MEM(SP@)
JMP Fback
LAB L7
MOVE VR@ VR(0)
SUB SP@ 3 SP
MOVE VR(0)@ MEM(SP@)(1)
ADD SP@ 2 SP
MOVE L8 MEM(SP@)
JMP Fprintf
LAB L8
SUB SP@ 2 SP
MOVE 0 VR(0)
MOVE VR(0)@ VR
MOVE FP@ SP
MOVE MEM(SP@)@ FP
SUB SP@ 1 SP
JMP MEM(SP@)@
MOVE FP@ SP
MOVE MEM(SP@)@ FP
SUB SP@ 1 SP
JMP MEM(SP@)@
LAB Fprintf
WRITE MEM(SP@)(-1)@
JMP MEM(SP@)@
LAB Fscanfi
READI MEM(SP@)(-1)@
JMP MEM(SP@)@
LAB Fscanff
READF MEM(SP@)(-1)@
JMP MEM(SP@)@
